# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import oauth2client.contrib.django_orm


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential', oauth2client.contrib.django_orm.CredentialsField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlowModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow', oauth2client.contrib.django_orm.FlowField(null=True)),
            ],
        ),
    ]
